version: '3'

vars:
  BIN_DIR: ./bin
  CMD_DIR: ./cmd

tasks:
  setup:
    cmds:
      - mkdir -p {{.BIN_DIR}}

  build:proto:
    desc: Build the protobuf files
    dir: pb
    cmds:
      - protoc *.proto --proto_path=. --go_out=. --go_opt=module=github.com/ericslandry/grpc/pb/greeter --go-grpc_out=. --go-grpc_opt=module=github.com/ericslandry/grpc/pb/greeter

  build:client:
    desc: Build the client application
    deps:
      - setup
    cmds:
      - go build -o {{.BIN_DIR}}/grpc-client {{.CMD_DIR}}/client

  build:server:
    desc: Build the server application
    deps:
      - setup
    cmds:
      - go build -o {{.BIN_DIR}}/grpc-server {{.CMD_DIR}}/server

  build:all:
    desc: Build both client and server applications
    cmds:
      - task: build:proto
      - task: build:client
      - task: build:server

  run:server:
    desc: Run the server application
    cmds:
      - "{{.BIN_DIR}}/grpc-server &"
      - "until grpcurl -proto ./pb/greeter.proto -plaintext localhost:8080 list; do printf '.'; sleep 1; done"

  run:client:
    desc: Run the client application
    cmds:
      - "{{.BIN_DIR}}/grpc-client --name=Mike"

  run:kill:
    desc: Stop the server application
    ignore_error: true
    silent: true
    cmds:
      - "pkill -f grpc-server"

  run:all:
    desc: Run both client and server applications (in parallel)
    cmds:
      - task: run:kill
      - task: run:server
      - task: run:client
      - task: run:kill

  default:
    desc: "Build and run both client and server"
    cmds:
      - task: build:all
      - task: run:all
